theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.2.24
  download_url: https://github.com/chrisant996/clink/releases/download/v1.2.24/clink.1.2.24.3a07c0.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.2.24/clink.1.2.24.3a07c0_setup.exe
