theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.1.30
  download_url: https://github.com/chrisant996/clink/releases/download/v1.1.30/clink.1.1.30.6ee82d.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.1.30/clink.1.1.30.6ee82d_setup.exe
